version: "3.8"
services:
  db:
    image: "postgres:alpine"
    container_name: "next-contact-db"

    environment:
      - POSTGRES_USER=alice
      - POSTGRES_PASSWORD=wonderland
      - POSTGRES_DB=next-contacts-db
    ports:
      - "54320:5432"
    volumes:
      - "./pg:/var/lib/postgresql/data"
